source 'http://rubygems.org'

# gem 'eureka-client', :git => 'git@github.com:mdsol/eureka-client.git', :tag => 'v2.5.4'
# gem 'rack-cache', :git => 'git@github.com:mdsol/rack-cache.git', :ref => 'afceb6134b20b992a51f8e19a2b007e3f4cecdf3'
# gem 'mdsol-tools', :git => 'git@github.com:mdsol/mdsol-tools.git', :tag => 'v0.3.2'
# gem 'mauth-client', :git => 'git@github.com:mdsol/mauth-client.git', :tag => 'v2.7.2'
# gem 'dice_bag', :git => 'git@github.com:mdsol/dice_bag.git', :tag => 'v0.8.0'
# gem 'shamus', :git => 'git@github.com:mdsol/shamus.git', :tag => '0.10.3'
# gem 'MediTAF', :git=> 'git@github.com:mdsol/MediTAF.git', :tag => 'v1.4.0'
# gem 'gem_goblin', :git=> 'git@github.com:mdsol/gem_goblin.git', :branch => 'develop'
gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'sauce-cucumber', :require => false
gem 'sauce'
gem 'sauce-connect'
gem 'site_prism'
gem 'retry', '~> 0.1.0'
gem 'with_retries', '~> 0.0.3'
gem 'poltergeist'
gem 'phantomjs'
gem 'rack-test'
gem 'cucumber'
gem 'MediTAF4', '~> 1.6'